### PR TITLE
Added new landing page

### PR DESCRIPTION
**Pull request by FaizAlam**

### CODE REVIEW

**Review by praveenscience — CHANGES_REQUESTED** [review]
Great one. Can we use hosted `bootstrap.css` from CDN and also, can you remove the `.DS_Store` files, please?

**Comment by FaizAlam** [comment]
Kindly check now.

**Comment by praveenscience** [comment]
Can we please have a hosted `bootstrap.css` using CDN and not include in the files? Thanks. 😁

**Comment by FaizAlam** [comment]
Here's the bootstrap cdn link **<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css">**
and also I deleted .DS_Store file in the latest commit. 

I can start a new PR and delete this one if you don't have any problem.
Thankyou

**Pull request closed without merging**
