### PR TITLE
simple  landing page

### PR DESCRIPTION
**Pull request by Arul-sathya**

### CODE REVIEW

**Comment by praveenscience** [comment]
Is this plagiarised from @briancodex's [`briancodex/html-css-js-website-smooth-scroll`: Simple website created using HTML, CSS & Javascript with smooth scroll effect](https://github.com/briancodex/html-css-js-website-smooth-scroll)?

**Comment by praveenscience** [comment]
The violation here is the third point. Please let me know if this is not right, I will be more than happy to listen... 😊 

image

**Comment by praveenscience** [comment]
I'll wait for another 14 hours before marking this... 👍🏻

**Comment by Arul-sathya** [comment]
> 

yes I changed it!

**Comment by praveenscience** [comment]
Nice one bro. Can we please please have it 2 space indented and XHTML?

**Review by praveenscience — CHANGES_REQUESTED** [review]
Nice one bro. Can we please please have it 2 space indented and XHTML?

**Comment by praveenscience** [comment]
Any updates? It's the last few hours of Hacktoberfest? 😁

**Pull request closed without merging**
