### PR TITLE
Created a news landing page.

### PR DESCRIPTION
**Pull request by divyanshraj0408**
Created a contained news landing page using gnews api and bootstrap.

### CODE REVIEW

**Comment by praveenscience** [comment]
Cool one man, can you please fix the linting issues and code indentation, thanks.

**Comment by divyanshraj0408** [comment]
Please check now

**Comment by praveenscience** [comment]
@divyanshraj0408 
image

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Technically:

- This is not a landing page.
- It's not responsive.

But I'm approving for your efforts. Learn about linting and indentation from the last two commits I made.

@divyanshraj0408 Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Comment by divyanshraj0408** [comment]
Thank You so much! I apologize for my inadequacy, I will surely learn about linting and indentation. I have already subscribed to your channel, You really help me a lot.

**Pull request merged**
