### PR TITLE
Added Covid 19 Landing Page

### PR DESCRIPTION
**Pull request by pccoder-2000**
Added my covid 19 Landing Page for this Hacktoberfest and put it under pccoder-2000 folder.

Screen shots:-
Full screen ss
small screen ss

### CODE REVIEW

**Comment by praveenscience** [comment]
Seems like it's not completely responsive. Do you wanna check it and fix it or should I merge it?

**Comment by pccoder-2000** [comment]
Modified the changes, Please merge it :)
small screen ss

**Comment by praveenscience** [comment]
Thanks for the attempt, it happens at this point:

image

**Review by praveenscience — APPROVED** [review]
Even though it's not upto the standards, I am happy for your attempt. 👍 

Feel free to make it better in next attempt.

**Comment by praveenscience** [comment]
@pccoder-2000 Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Pull request merged**
