### PR TITLE
Added responsive landing page with navbar for an EdTech platform

### PR DESCRIPTION
**Pull request by poonervikas**
Created a responsive landing page with navbar for an EdTech platform.

### CODE REVIEW

**Comment by poonervikas** [comment]
Please merge the pull request.

**Comment by poonervikas** [comment]
...

**Comment by praveenscience** [comment]
Also, why did you close the PR? 🤔

**Comment by poonervikas** [comment]
Hi,

I reminded you twice earlier.So I thought you didn't liked it or not looked
into it that's why I closed the pr.

**Pull request closed without merging**
